AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Serverless Application.

Resources:
  GPTCaller:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.10
      CodeUri: .
      Description: OpenAI APIを使ってGPTにプロンプトを投げる
      MemorySize: 512
      Timeout: 10
      Policies: AWSLambdaBasicExecutionRole
